name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Rebuild the dist/ directories
        run: |
          pnpm run -r build
          pnpm run -r package

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: 'us-east-1'
      TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
      TF_BACKEND_BUCKET_REGION: 'us-east-1'
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: gh-action-winglang
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - uses: ./actions/deploy
        name: "Plain Wing app"
        with:
          entry: 'main.w'
          working-directory: './examples/plain'
          target: 'tf-aws'
          backend: 's3'